#!/bin/bash
# snake
#
# Show the parent dir path from the current directory.
#
# 0.0.0: show a helper message using -h after the script call
#
# Chicoo Freitas, 
# chicoo.freitas84@gmail.com
# May, 23. 2024
#
################################################################################



################################################################################

# Check if the container ID or name is passed
#if [ -z "$1" ]; then
#    echo "Usage: $0 <container_name_or_id> <command> [args...]"
#    exit 1
#fi

# Get the container name or ID
CONTAINER_NAME="django-starter-container-app-web-1"

# Shift to remove the first argument (container name) and keep the command and its arguments
#shift

# Check if a command is provided
if [ -z $1 ]; then
    echo "Please provide a command to run inside the container."
    exit 1
fi

# Execute the command inside the specified Docker container
docker exec -it "$CONTAINER_NAME" "$@"
